### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by ibowden** [massedge/wordpress-plugin-export-media-library#1]
I'm rebuilding a website from scratch and want to reuse much of the media for the old site in the new site and figured your plugin was the answer. Every time I run the plugin and click the 'download zip' button, I get the 'file not found' error in the resulting new tab in my browser. Any reason you can figure?
Cheers!
Ian

**Comment by andrejpavlovic** [comment]
Do you know your Wordpress and PHP version?

**Comment by ibowden** [comment]
WP is 4.9.8.

PHP is 7.2.11

Cheers!

Ian

**Comment by andrejpavlovic** [comment]
What is the URL when you go to the Export page, and then what is the URL once you click the Download Zip button?

**Comment by michaelcargo** [comment]
Hello, 
I am running into this same issue. I am not sure if the library size is a too large. I have tested the download with various options selected and getting the same error each time.

**Comment by andrejpavlovic** [comment]
@michaelcargo It is most likely not an issue with library size if it didn't even begin to download.

**Comment by michaelcargo** [comment]
Thank you, I was able to sort this out using a FTP transfer.

**Comment by andrejpavlovic** [comment]
@nexjsystems It seems to be a recurring issue, but I've never been able to reproduce it on any of my hosting servers. Who is your hosting provider? Ideally you or someone would be able to setup a separate site where I can login and try to figure out what's going on. Otherwise my hands are pretty much tied...

**Comment by andrejpavlovic** [comment]
I've updated the plugin to version 2.2.0. Give it a try and let me know if it helps with your issue.

**Comment by andrejpavlovic** [comment]
Closing due to lack of response.
