### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by ishimarumakoto** [massedge/wordpress-plugin-export-media-library#14]
Can find the *.zip generated by the plugin inside the file system of the server.

**Comment by andrejpavlovic** [comment]
There is no zip file stored on the server - the zip file is generated dynamically as you download it.

**Comment by ishimarumakoto** [comment]
> 
> 
> There is no zip file stored on the server - the zip file is generated dynamically as you download it.

Hey, thanks for the reply.
I'm having issues using firefox. I click on the download and the download never completes (miss 3mb or so).
Using Chrome worked fine.
Can I help in some debugging in my side?
Firefox 67.0

**Comment by ryanadiaz** [comment]
In case someone else encounters this issue...

The .zip file that this plugin creates was not opening for me.  I renamed the file .tar, and then I was able to open it just fine.

**Comment by andrejpavlovic** [comment]
@ishimarumakoto - i'm not sure what the problem would be with firefox specifically... I tried it myself and it's working fine.

@ryanadiaz - when you changed the extension, did it result in opening the file with a different program? I don't see why just changing the extension would make a different.

**Comment by ryanadiaz** [comment]
@andrejpavlovic - I was using Chrome.  It generated a .zip file and allowed to fully download it.  Opening it or extracting it using 7zip resulted in an error.  I renamed it .tar, and then 7zip opened it with no issue.

**Could be specific to using 7zip.**
