### ISSUE TITLE
Exclude .gitignore from your distribution build

### ISSUE THREAD

**Issue by RobertGres** [massedge/wordpress-plugin-export-media-library#16]
Hi!

.gitignore file causes vendor directory to be excluded in projects managed by git. This results in vendor directory being missing on other environments I deploy to - and crashes everything of course.

I cannot override its behavior, so the only way to fix it for me is to remove your .gitignore. The problem is that after next update it's going to appear again - and cause trouble.

You can remove composer.json and composer.lock.json as well since they make sense only for the packages managed by composer itself.

Alternatively you can publish your plugin to packagist or wp-packagist, so composer users would be able to just declare it in their project's composer.json (I see that you've declared "type": "wordpress-plugin" in plugin's composer.json, but including it directly from github isn't an option for me)

**Comment by andrejpavlovic** [comment]
Removed `.gitignore` and `composer.*` files from the build. Thanks for the report.

**Comment by andrejpavlovic** [comment]
Closing due to lack of feedback.
