### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by PAK43** [massedge/wordpress-plugin-export-media-library#17]
From WordPress email:
Error Details
=============
An error of type E_ERROR was caused in line 461 of the file /......l/wordpress/wp-content/plugins/export-media-library/vendor/maennchen/zipstream-php/src/ZipStream.php. Error message: Allowed memory size of 268435456 bytes exhausted (tried to allocate 155205632 bytes)

**Comment by andrejpavlovic** [comment]
Thanks for the bug report. Try the latest version (3.0.0) if you get the chance. The plugin should be using less memory now.

**Comment by PAK43** [comment]
That fixed it! Downloaded 400MB. Thank you.

**Comment by andrejpavlovic** [comment]
Awesome! Thanks for letting me know :)
