### ISSUE TITLE
ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by rsinusas** [massedge/wordpress-plugin-export-media-library#18]
I have been trying for days and I keep getting

This site can’t be reachedThe webpage at https://www.XXXXXX.com/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by andrejpavlovic** [comment]
Duplicate of #13
