### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by brownrl** [massedge/wordpress-plugin-export-media-library#19]
PHP Fatal error:  Uncaught Error: Class 'MassEdge\WordPress\Plugin\ExportMediaLibrary\Plugin' not found in xxxxxxxx/wordpress/wp-content/plugins/export-media-library/run.php:9

Stack trace:
....

plugin breaks wp-cli

**Comment by andrejpavlovic** [comment]
Are you installing this plugin via composer directly from github? Not sure if the latest version will work for you, but give it a try when you get the chance. Also, are you using wp-cli.phar, or the composer way of installing it?

**Comment by andrejpavlovic** [comment]
Closing due to lack of feedback.
