### ISSUE TITLE
wordpress.com - 500 Internal Server Error

### ISSUE THREAD

**Issue by sopmac** [massedge/wordpress-plugin-export-media-library#2]
Hello 

I installed your plugin on a site on wordpress.com, but it doest work, it give me de following error

500 Internal Server Error
An error occurred while processing this request.

Website owner? Check your code and/or debug log. If you need assistance, contact support.

Can you please help me

**Comment by sopmac** [comment]
Hello 

I select Nested folders com compress “yes” when i click on download zip it give me that error

Regards





Antes de imprimir, pense no MEIO AMBIENTE

AVISO LEGAL
Esta mensagem é destinada exclusivamente para a(s) pessoa(s) a quem é dirigida, podendo conter informação confidencial e/ou legalmente privilegiada. Se você não for destinatário desta mensagem, desde já fica notificado de abster-se a divulgar, copiar, distribuir, examinar ou, de qualquer forma, utilizar a informação contida nesta mensagem, por ser ilegal. Caso você tenha recebido esta mensagem por engano, pedimos que nos retorne este E-Mail, promovendo, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle. Fica desprovida de eficácia e validade a mensagem que contiver vínculos obrigacionais, expedida por quem não detenha poderes de representação.

Before printing, think about the ENVIRONMENT

LEGAL ADVICE
This message is exclusively intended for the people to whom it is addressed, and it may contain confidential and/or legally privileged information. If you are not an addressee of this message, you are hereby notified not to disclose, copy, distribute, review or otherwise use the information contained in this message, because it is illegal. If you received this message by mistake, we ask you to return this e-mail to us, and proceed as soon as possible to remove its contents from your database, registrations, or control system. Any message that contains any mandatory links, issued by any unauthorized person, shall be null or void.

**Comment by andrejpavlovic** [comment]
PHP, server, wordpress versions?

**Comment by sopmac** [comment]
Hello 

The version of php is 7.0.32 the server is WordPress.com's server and the version o wp is Version 4.9.8

regards






Antes de imprimir, pense no MEIO AMBIENTE

AVISO LEGAL
Esta mensagem é destinada exclusivamente para a(s) pessoa(s) a quem é dirigida, podendo conter informação confidencial e/ou legalmente privilegiada. Se você não for destinatário desta mensagem, desde já fica notificado de abster-se a divulgar, copiar, distribuir, examinar ou, de qualquer forma, utilizar a informação contida nesta mensagem, por ser ilegal. Caso você tenha recebido esta mensagem por engano, pedimos que nos retorne este E-Mail, promovendo, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle. Fica desprovida de eficácia e validade a mensagem que contiver vínculos obrigacionais, expedida por quem não detenha poderes de representação.

Before printing, think about the ENVIRONMENT

LEGAL ADVICE
This message is exclusively intended for the people to whom it is addressed, and it may contain confidential and/or legally privileged information. If you are not an addressee of this message, you are hereby notified not to disclose, copy, distribute, review or otherwise use the information contained in this message, because it is illegal. If you received this message by mistake, we ask you to return this e-mail to us, and proceed as soon as possible to remove its contents from your database, registrations, or control system. Any message that contains any mandatory links, issued by any unauthorized person, shall be null or void.

**Comment by sopmac** [comment]
they gave me this info too

You can also give them this info regarding your server, it may help as well - 'Linux web28.q4.sat.pressable.net 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64’

Regards






Antes de imprimir, pense no MEIO AMBIENTE

AVISO LEGAL
Esta mensagem é destinada exclusivamente para a(s) pessoa(s) a quem é dirigida, podendo conter informação confidencial e/ou legalmente privilegiada. Se você não for destinatário desta mensagem, desde já fica notificado de abster-se a divulgar, copiar, distribuir, examinar ou, de qualquer forma, utilizar a informação contida nesta mensagem, por ser ilegal. Caso você tenha recebido esta mensagem por engano, pedimos que nos retorne este E-Mail, promovendo, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle. Fica desprovida de eficácia e validade a mensagem que contiver vínculos obrigacionais, expedida por quem não detenha poderes de representação.

Before printing, think about the ENVIRONMENT

LEGAL ADVICE
This message is exclusively intended for the people to whom it is addressed, and it may contain confidential and/or legally privileged information. If you are not an addressee of this message, you are hereby notified not to disclose, copy, distribute, review or otherwise use the information contained in this message, because it is illegal. If you received this message by mistake, we ask you to return this e-mail to us, and proceed as soon as possible to remove its contents from your database, registrations, or control system. Any message that contains any mandatory links, issued by any unauthorized person, shall be null or void.

**Comment by kristensoils** [comment]
I am having the same problem. Wordpress.com has disabled nearly every plugin that will allow me to migrate my 11-year-old site to another host easily, doesn't allow FTP access and charges an arm and a leg for restricted, limited managed WordPress hosting. So I am trying to manually migrate everything over, but my 2G media library is a HUGE speedbump since their export tools won't export any library files newer than 3 months old. I just want to download a compressed file and be done with it since I can't get FTP access but keep getting the same 500 Internal Server Error message every time I try. This plugin seems the only one that is still being supported so I'm really hoping that this issue can be overcome before I get charged another $326 by Wordpress.com for hosting and domain (total rip off!).

**Comment by andrejpavlovic** [comment]
@kristensoils Sorry to hear that, but unfortunately I don't have access to a wordpress.com account, so I haven't been able to try and figure out what the problem is.

**Comment by andrejpavlovic** [comment]
I've updated the plugin to version 2.2.0. Give it a try and let me know if it helps with your issue.

**Comment by andrejpavlovic** [comment]
Closing due to lack of response.
