### ISSUE TITLE
Empty Zip

### ISSUE THREAD

**Issue by zChris83** [massedge/wordpress-plugin-export-media-library#21]
Hello, i have installed your plugin. But when do an export the zip file is empty.

What am i doing wrong ?

**Comment by andrejpavlovic** [comment]
How big is the zip file?

**Comment by zChris83** [comment]
26 bytes

**Comment by andrejpavlovic** [comment]
Can you try opening it in notepad as a regular text file? There might be an error message

**Comment by zChris83** [comment]
Yeah all it says is this 

"PK                  "

without the snuffs (")

**Comment by andrejpavlovic** [comment]
Hmm, that doesn't tell me much. Let me know who is your hosting provider and PHP version number, but I think without setting up a test site based on your database/files, it's going to be hard to figure out what's the problem.

**Comment by andrejpavlovic** [comment]
Closed due to lack of feedback.
