### ISSUE TITLE
API Export samples?

### ISSUE THREAD

**Issue by smvueno** [massedge/wordpress-plugin-export-media-library#23]
Hi! I'm looking for API documentation of some kind?

Simply speaking I want to create a "download all photos" button on my album pages.

I am a beginner when it comes to PHP, but I would really love to try and get the export API going!
Is anyone able to give some samples for how to call the API and then download a folder or multiple files?

Kind regards, Jens

**Comment by andrejpavlovic** [comment]
This should give you some idea how to export a custom set of files:
https://github.com/massedge/wordpress-plugin-export-media-library/issues/9#issuecomment-487979735

**Comment by andrejpavlovic** [comment]
Closing due to lack of feedback.
