### ISSUE TITLE
Will your plugin  export a way to associate the thumbnail and image?

### ISSUE THREAD

**Issue by iigkid** [massedge/wordpress-plugin-export-media-library#24]
For example:

Can I map:
_thumbnail_id: '15398'
to:
IMG_5825-780x300.jpg

Thank you!

**Comment by andrejpavlovic** [comment]
The plugin currently only supports exporting original files. Resized images are not included in the export.

**Comment by andrejpavlovic** [comment]
Closing due to lack of feedback.
