### ISSUE TITLE
Exporting All files

### ISSUE THREAD

**Issue by lovleenaprasad** [massedge/wordpress-plugin-export-media-library#26]
hi there
I was just wondering - once the files are exported are they then deleted from the media library.
Do all he files get exported? or only original images?
Is there an export limit? 1232 items in the media library.
Thank you

**Comment by andrejpavlovic** [comment]
It doesnt delete any files.
Only original files get exported, not resized images.
You should be able to export at least a few gigabytes worth of files no problem, as long as your internet connection is reliable.

**Comment by lovleenaprasad** [comment]
Thank you for getting back to me - i am still having trouble with the exporting. It may be the internet connection. Is there a way to export media files in batches.
Thank you

**Comment by andrejpavlovic** [comment]
No exporting in batches with this plugin. You can look into some other plugins that do backups, or copy the files over using FTP.

**Comment by andrejpavlovic** [comment]
Issue has become stale. Please reopen if further assistance needed.
