### ISSUE TITLE
Unsupported Version

### ISSUE THREAD

**Issue by tempoeric** [massedge/wordpress-plugin-export-media-library#27]
Hi its not supported for 7.0 or lower php can we do it as to php 5 and up to latest so we can use it? thanks

**Comment by andrejpavlovic** [comment]
You can try using one of the older versions. Go to https://wordpress.org/plugins/export-media-library/advanced/ and scroll all the way to the bottom. Version 2.2 should support PHP 7.0+ and version 1.1 PHP 5.6+

**Comment by tempoeric** [comment]
my version of php is 5.5 and its already in the production stage so I want to download all media files before updating it just incase something happens

**Comment by tempoeric** [comment]
can i ask for a version 5.5

**Comment by andrejpavlovic** [comment]
You should probably do a full backup if you are doing an upgrade. Export is more for people who want to quickly be able to do something with their media files offline.

Unfortunately I only have the time to support the latest version of the plugin which requires PHP 7.1+

**Comment by andrejpavlovic** [comment]
Issue has become stale. Please reopen if further assistance needed.
