### ISSUE TITLE
Plugin Wont Activate

### ISSUE THREAD

**Issue by jeffmastro** [massedge/wordpress-plugin-export-media-library#3]
I can get the plugin to activate. no error. just refreshes the page and then still inactive and no option in the media menu

**Comment by andrejpavlovic** [comment]
Hmm, what's the WordPress and PHP version?

**Comment by jeffmastro** [comment]
1st thank you so much for the prompt reply. I did see an error that said i didnt have a high enough version of PHP. the site is hosted by someone else so i dont know how much control i have over that 
 
--------- Original Message --------- Subject: Re: [massedge/wordpress-plugin-export-media-library] Plugin Wont Activate (#3)

**Comment by andrejpavlovic** [comment]
Minimum supported PHP version is 5.6 and up. It is not possible for the plugin to run on anything lower than that.
