### ISSUE TITLE
Feature Request: More descriptive file name for zip

### ISSUE THREAD

**Issue by MadtownLems** [massedge/wordpress-plugin-export-media-library#32]
I think it would be great if the zip's name could include the blog's name.  Something maybe like:

$name = strtolower( get_option('blogname') );
$name = str_replace( ' ', '-', $name );
$name = preg_replace('/[^a-z-]/i','',$name );
$name = sanitize_file_name( $name );

$zip_name =  $name . '-media-files-' . date('Y-M-d') . '-' . time() .  '.zip';

This would be useful for most people, I imagine, but especially useful for people who manage multiple sites (including MultiSite).

**Comment by andrejpavlovic** [comment]
Good idea, I'll look into it.

**Comment by andrejpavlovic** [comment]
version 3.0.1 includes timestamp and blog name in the exported filename
