### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by zkm** [massedge/wordpress-plugin-export-media-library#34]
Attempted to download and activate your plugin but was unable to due to this parse error. 
----
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in .../wp-content/plugins/export-media-library/index.php on line 17
----

WP v4.2.27

**Comment by andrejpavlovic** [comment]
Plugin supports PHP 7.1+. You're probably running a very old version of PHP.

**Comment by zkm** [comment]
You're probably not wrong. Thank you for the quick response.
