### ISSUE TITLE
Export Media Library Plugin not working

### ISSUE THREAD

**Issue by avtechies** [massedge/wordpress-plugin-export-media-library#35]
I activated the plugin, exported the images to a zip file, tried to open in Windows and WinZip, neither one worked. I get an error saying: "Cannot open file xxx.zip does not appear to be a valid archive. If you downloaded the file try downloading it again."
![export library error](https://user-images.githubusercontent.com/65873248/82765857-49ca3080-9dcf-11ea-86f7-5dda78db1cd4.png)

**Comment by andrejpavlovic** [comment]
See https://github.com/massedge/wordpress-plugin-export-media-library/issues/5#issuecomment-469114158

**Comment by andrejpavlovic** [comment]
Issue has become stale. Please reopen if further assistance needed.
