### ISSUE TITLE
Impossible to reach /site/mass-edge-export-media-library

### ISSUE THREAD

**Issue by JEricaM** [massedge/wordpress-plugin-export-media-library#4]
Hi,
I've installed this plugin but I'm not able to use it. When I click on the "Download zip" button, a new tab it's open with an error:
```
Impossible to reach site
The web page at https://www.mysite.it/wp-admin/upload.php?page=mass-edge-export-media-library it may be temporarily unavailable or has been permanently moved to a new web address.
```
![senza titotyuhuuylo 1](https://user-images.githubusercontent.com/9347586/53010265-bec8f080-343d-11e9-9cd7-82265bb37dac.png)

I tried a lot of times, but I always have the same error.
Someone can help? 
Thank you in advance.

**Comment by andrejpavlovic** [comment]
PHP version? zip enabled?

**Comment by dgadwa** [comment]
FWIW, I'm getting the same thing, running PHP version 7.1.  

This site can’t be reached The webpage at http://xxxxxxxx.flywheelsites.com/wp-admin/upload.php?page=mass-edge-export-media-library might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE


I might try disabling other plugins later.  Any thoughts?

**Comment by andrejpavlovic** [comment]
Who is your hosting provider?

**Comment by andrejpavlovic** [comment]
I've updated the plugin to version 2.2.0. Give it a try and let me know if it helps with your issue.

**Comment by andrejpavlovic** [comment]
Closing due to lack of response.
