### ISSUE TITLE
The number of downloaded images did not match the number of images in the library

### ISSUE THREAD

**Issue by mmoser-markl** [massedge/wordpress-plugin-export-media-library#41]
In the WordPress Media Library, you can see how many images are currently uploaded. Mine is 862 items. After using this plugin to export all images, the total images downloaded is only 667. I'm not sure what images are not downloaded or why it skipped it. 

Are there any ways to resolve this?

Thanks!

**Comment by andrejpavlovic** [comment]
Try finding which images were not downloaded. Maybe the files are missing from the server.

**Comment by mmoser-markl** [comment]
I used Beyond Compare to compare folders that's been downloaded and the photos that are on the server. I realized that it did not downloaded the size variants - only the full size which is good. But there are also images on the server that are 0kb which it also did not downloaded. 

So overall, the plugin actually downloaded the images that matter so that's great!
