### ISSUE TITLE
May we get an update this awesome plugin?

### ISSUE THREAD

**Issue by arsh999cg** [massedge/wordpress-plugin-export-media-library#44]
Wordpress shows that the plugin is not updated from 3 major, Screenshot attached below.

[WordPress update notice](https://paste.pics/IFTRO)

Can we get an update for this awesome plugin? It is working fine for me until now, so if it is not needed to change the code, then only please update the plugin version to get it update and this would remove the wordpress notice.

**Comment by paaljoachim** [comment]
I agree! It would be very helpful to get an update.

**Comment by andrejpavlovic** [comment]
Bumped plugin version to `4.0.0`. Minimum PHP version is now `7.4`

**Comment by arsh999cg** [comment]
Thanks.

**Comment by paaljoachim** [comment]
Yes, thank you Andrej!
