### ISSUE TITLE
Only half of my media library is exporting

### ISSUE THREAD

**Issue by d-glz12** [massedge/wordpress-plugin-export-media-library#48]
I'm trying to download a media library but it only downloads half of the available items. Is there a limit to how many items I can export?

**Comment by andrejpavlovic** [comment]
There isn't a limit.  How many items are in the library vs how many are exported? What's the size of the exported zip?

**Comment by andrejpavlovic** [comment]
Duplicated of https://github.com/massedge/wordpress-plugin-export-media-library/issues/45
