### ISSUE TITLE
Windows cannot open the folder - error

### ISSUE THREAD

**Issue by GJF100** [massedge/wordpress-plugin-export-media-library#5]
Hello, 

I've downloaded an export file a couple of times using either the compressed or non-compressed options and each time a file downloads which appears to have a size expected from the sum of the images, but when I try to open the ZIP or Extract the ZIP, I get the following windows error:

"Windows cannot open the folder. 

The Compressed (Zipped) Folder 'C:\...FileName' is invalid. 

Any ideas or advice, please?

Many thanks.

**Comment by andrejpavlovic** [comment]
Hmm, not sure, try using a different decompressor. See if [7zip](https://www.7-zip.org/) can open it.

**Comment by GJF100** [comment]
Hey Andrej, thanks for the quick follow up. That's worked, a couple of errors during the process, but the images there. Cheers
