### ISSUE TITLE
Export Media Libary

### ISSUE THREAD

**Issue by robywoo** [massedge/wordpress-plugin-export-media-library#50]

**Comment by robywoo** [comment]
I downloaded the export media plugin to my computer but I don't know how to know add the plugin to my site. I have gone to my plugin page and tried to add the file but I don't know what file to add. It did not download as a zip file, just an export media library folder with lots of other folders in it

**Comment by robywoo** [comment]
I think I have done it. I zipped it then added the plugin

**Comment by andrejpavlovic** [comment]
Great!
