### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by mponyboy** [massedge/wordpress-plugin-export-media-library#51]
Hi, Running WordPress 6.2.2. Installed plugin, run, as I'm watch the folder I'm downloading to, it bails on download. If I restart in Chrome, file in folder is only 100 kb and I get error saying file is invalid. Even with Zip7.
Thanks

**Comment by andrejpavlovic** [comment]
If the downloaded file is that small, try opening the file in notepad or some editor and see if there is an error message in the text somewhere.

**Comment by mponyboy** [comment]
Found a few, this was the first. I thought I had deactivated Smush.
<script id='smush-js-js-extra'>
var wposmush = {"all_images_compressed":"No uncompressed images were found.","error_unexpected_response":"An unexpected response was received from the server. More information has been logged in the browser console.","compress_single_image_dialog":"Please wait: compressing the selected image.","error_try_again_later":"Please try again later.","server_check":"Connecting to the Smush API server, please wait","please_wait":"Please wait while the request is being processed","server_error":"There was an error connecting to the image compression server. This could mean either the server is temporarily unavailable or there are connectivity issues with your internet connection. Please try later.","please_select_images":"Please select the images you want compressed from the \"Uncompressed images\" panel first","please_updating_images_info":"Please wait: updating information about the selected image.","please_select_compressed_images":"Please select the images you want to mark as already compressed from the \"Uncompressed images\" panel first","view_image":"View Image","delete_image_backup_confirm":"Do you really want to delete all backup images now? This action is irreversible.","mark_all_images_uncompressed":"Do you really want to mark all the images as uncompressed? This action is irreversible.","restore_images_from_backup":"Do you want to restore the original images from the backup (where they exist?)","restore_all_compressed_images":"Do you really want to restore all the compressed images?","more":"More","less":"Less","converting_to_webp":"Converting image to WebP format, please wait","ajaxurl":"https:\/\/www.adventurezoneduluth.com\/wp-admin\/admin-ajax.php","features":{"resmushit":{"max_filesize":5242880,"lossy_compression":false,"preserve_exif":true}},"smush_ajax_nonce":"fa9b9c7b19"};
</script>

**Comment by mponyboy** [comment]
I had tried downloading yesterday and again today.

**Comment by andrejpavlovic** [comment]
Hmm, not sure what's going on - maybe some other plugin is interfering with this one. You might need to disable them one at a time. Not sure else I could suggest.

**Comment by mponyboy** [comment]
I might try that or do an entire site download and dig them out of image folder.
Thanks.

**Comment by mponyboy** [comment]
Hi. I reinstalled the plug-in today and ta-da, it worked! Might have been the WordPress version update or that it's a Wednesday. I thought I'd let you know.
Thanks.

**Comment by andrejpavlovic** [comment]
Glad it worked out!
