### ISSUE TITLE
If you're considering stepping away from maintaining this plugin, please take this into consideration.

### ISSUE THREAD

**Issue by mamunur105** [massedge/wordpress-plugin-export-media-library#53]
It seems like there's still potential for it to be useful, and I'm eager to contribute to its development. 
Let me know your thoughts on this.

**Comment by andrejpavlovic** [comment]
PRs are always welcome

**Comment by mamunur105** [comment]
Kindly include me as a contributor on GitHub and grant me SVN access for committing to the WordPress Repository. I assure you, I'll handle it diligently.
