### ISSUE TITLE
archives are corrupt and wont expand

### ISSUE THREAD

**Issue by jeffmastro** [massedge/wordpress-plugin-export-media-library#6]
Im on a Mac with Mojave and have tried expanding with the finder and with terminal and Stuffit Expander and each time it says the zip file created with the plugin may be corrupt. Terminal actually says its missing the end of central directory signature.

please advise

**Comment by andrejpavlovic** [comment]
Hmm, I'm not sure. I've been able to export and expand the archive on OSX Mojave fine.. Does the size of the zip file make sense? How big is it? Also, did you try the compressed vs uncompressed export?

**Comment by jeffmastro** [comment]
136 mb and yes both compressed and uncompressed yield same results 

Jeff Mastromonico
Mastromonico.com
Twitter.com/jeffm
Facebook.com/jeffmastromonico

**Comment by andrejpavlovic** [comment]
Probably running out of options here... PHP version? Hosting provider?

**Comment by jeffmastro** [comment]
5.6 but I didn’t set up this site so I don’t know the host. Btw thank you for your time and attention 

Jeff Mastromonico
Mastromonico.com
Twitter.com/jeffm
Facebook.com/jeffmastromonico

**Comment by andrejpavlovic** [comment]
I've updated the plugin to version 2.2.0. Give it a try and let me know if it helps with your issue.

**Comment by jeffmastro** [comment]
Cool. Thank you very much. Will let you know 

Jeff Mastromonico
Mastromonico.com
Twitter.com/jeffm
Facebook.com/jeffmastromonico

**Comment by andrejpavlovic** [comment]
Closing due to lack of response.
