### ISSUE TITLE
I LOVE your plugin!

### ISSUE THREAD

**Issue by christinahills** [massedge/wordpress-plugin-export-media-library#7]
I just wanted to say how much I LOVE your plugin
https://wordpress.org/plugins/export-media-library/
it does exactly what I want it to.  Just export the media library
and allows me to export to one folder.

It's so simple, and works really well and is totally intuitive!

I'd like to promote it on twitter, but could not find your twitter name.

:) Christina
@christinahills (on twitter)

**Comment by andrejpavlovic** [comment]
I'm glad you found it useful. Thanks for spreading the word :)

Maybe I'll setup a twitter account one day, but don't have one at the moment.
